apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: distribusion
  labels:
    app: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: dockercloud/hello-world
        name: helloworld
        ports:
        - containerPort: 80
      restartPolicy: Always
