apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: distribusion
  labels:
    app: helloworld
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: helloworld
  type: NodePort
